### ISSUE TITLE
Error upon executing the notebook - live.zip is not available

### ISSUE THREAD

**Issue by VVasanth** [ocampor/image-quality#20]
Hi,

I am facing error while executing the python notebook and upon analyzing the issue - found that the zip file hosted in the location does not work.

In 'live_iqa.py' file, url mentioned in 'live_url' (live_url = "https://data.ocampor.ai/image-quality/live.zip") file is not working. Could you please help me fix this issue?

Thanks,
V.Vasanth

**Comment by ocampor** [comment]
Hello, this was fixed and updated. Thanks!
