### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'homepage' while trying to run the notebook "train-diqa-base"

### ISSUE THREAD

**Issue by Nymeria18** [ocampor/image-quality#25]
When i run 
builder = imquality.datasets.LiveIQA()
builder.download_and_prepare()
I get the aforementioned error with 

TypeError                                 Traceback (most recent call last)
<ipython-input-32-1dbb51f702d0> in <module>
----> 1 builder = imquality.datasets.LiveIQA()
      2 builder.download_and_prepare()

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     allowed: Optional[List[str]] = ...,
     51 ) -> Callable[[Fn], Fn]:
---> 52   ...
     53 @typing.overload
     54 def disallow_positional_args(wrapped: Fn, allowed: None = ...) -> Fn:  # pylint: disable=g-wrong-blank-lines

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py in __init__(self, data_dir, config, version)
    186         even if not default. This is not recommended unless you know what you
    187         are doing, as the version could be broken.
--> 188     """
    189     # For pickling:
    190     self._original_state = dict(data_dir=data_dir, config=config,

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py in __get__(self, obj, objtype)
    115 
    116   Will raise an error if the user try to overwrite one key. The error message
--> 117   can be customized during construction. It will be formatted using {key} for
    118   the overwritten key.
    119   """

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py in info(self)
    232         utils.Version(v) if isinstance(v, six.string_types) else v
    233         for v in [self.canonical_version] + self.supported_versions
--> 234     ]
    235 
    236   def _pick_version(self, requested_version):

~/Downloads/image-quality-master/imquality/datasets/live_iqa.py in _info(self)
     74             citation=CITATION,
     75             redistribution_info={
---> 76                 'license': LICENSE,
     77             },
     78         )

~/anaconda3/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     allowed: Optional[List[str]] = ...,
     51 ) -> Callable[[Fn], Fn]:
---> 52   ...
     53 @typing.overload
     54 def disallow_positional_args(wrapped: Fn, allowed: None = ...) -> Fn:  # pylint: disable=g-wrong-blank-lines

TypeError: __init__() got an unexpected keyword argument 'homepage'

Please help how to fix this.

**Comment by ocampor** [comment]
Sorry, but I could not afford the prices of hosting the file anymore.
