### ISSUE TITLE
ValueError: the input array must have size 3 along `channel_axis`, got (151, 181, 4)

### ISSUE THREAD

**Issue by np-n** [ocampor/image-quality#42]
**ValueError: the input array must have size 3 along `channel_axis`, got (151, 181, 4)**

I am trying image-quality library to find the quality of mage.I write following code according to your documentation.
```import imquality.brisque as brisque
import PIL.Image
import cv2
path = '/home/npn/Downloads/npn_img.png'
img = PIL.Image.open(path)
print(brisque.score(img))```


But I am expecting the score of image.How to address this issue.

**Comment by njay225** [comment]
https://github.com/ocampor/image-quality/issues/41#issuecomment-1011477402

**Comment by HodeiG** [comment]
@np-n could you check whether converting the image to RGB fixes your issue?

```
import PIL.Image
import cv2
path = '/home/npn/Downloads/npn_img.png'
img = PIL.Image.open(path)
img = img.convert('RGB')
print(brisque.score(img))
```

**Comment by pl4yb0yz2001** [comment]
According to https://github.com/ocampor/image-quality/issues/41#issuecomment-1011477402, you can replace line 45 of `imquality/brisque.py' with:
```
# Only convert image to grayscale if RGB
if self.image.shape[-1] == 3:
    self.image = skimage.color.rgb2gray(self.image)
```
=> Problem solved

**Comment by np-n** [comment]
Solved when I have replaced line 45 of imquality/brisque.py with 

`# Only convert image to grayscale if RGB
if self.image.shape[-1] == 3:
    self.image = skimage.color.rgb2gray(self.image)`

**Comment by np-n** [comment]
Changing the color space of image solved the issue.
